version: '3.8'

services:
  web_convert_file:
    build: .
    volumes:
      - ./:/core
    ports:
      - 8000:8000
    depends_on:
      - db_convert_file
    env_file:
      - .env

  db_convert_file:
    image: postgres:13.2
    restart: always
    command: -p 5000
    ports:
      - 5000:5432
    volumes:
      - postgres_data_convert_file:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data_convert_file: